### ISSUE TITLE
[MAJOR] Bottleneck issues (test, search function, refactoring)

### ISSUE THREAD

**Issue by HarimbolaSantatra** [HarimbolaSantatra/mm-cli#46]
## DESCRIPTION
In the `Morphologie` section, there is:
```
Morphologie:
Simple :lakozia
        - lakoziako
        - lakozianao
        - lakoziany
        - lakoziantsika
        - lakozianay
        - lakozianareo
        - lakozian'
        - lakozian-
        - lakoziam-Préfixée :-dakozia
        - -dakoziako
        - -dakozianao
        - -dakoziany
        - -dakoziantsika
        - -dakozianay
        - -dakozianareo
        - -dakozian'
        - -dakozian-
        - -dakoziam-
```

`Simple` and `Préfixée` are two sub-section that is not highlighted clearly on the output of the CLI.

## Ideal
```
Morphologie:
    Simple:
        - lakozia
        - lakoziako
        - lakozianao
        - lakoziany
        - lakoziantsika
        - lakozianay
        - lakozianareo
        - lakozian'
        - lakozian-
        - lakoziam
    Préfixée:
        -dakozia
        - -dakoziako
        - -dakozianao
        - -dakoziany
        - -dakoziantsika
        - -dakozianay
        - -dakozianareo
        - -dakozian'
        - -dakozian-
        - -dakoziam-
```

In order to solve this, we need to refactor the code first. So that's the cause of the *[MAJOR]* signals  and *major* tag come from.

## TASKS
- [x] #50 
- [x] Implement a struct for the output of the parsing operation
    - [x] Use the struct `ParsedContent` as argument to `PrintResult(...)`
- [ ] Add tests
    - [ ] A test for `ParseString`: take `result.html` as input and check if it returns the `ParsedContent` object representing `parsing-result.json`
